SPREADSHEET: 1VmZJErRoQi099PWj0m8oeMMvta5cjroxLNA3HrcLXCk
SCOPES: ["https://www.googleapis.com/auth/spreadsheets.readonly"]
GO: Graphene based NMs
SiO2: silica
SdopedTiO2SiO2: sdoped
ZnO: ZnO
Ag: Ag
Fe3O4: Fe3O4
Al: Al
EMAIL: javier.millanacosta@maastrichtuniversity.nl